.github/workflows/release-cli.yml, README.md
build and upload binaries for linux and darwin when a `v*` tag is pushed
=> workflow to release binaries

cmd/resim/commands/batch.go, cmd/resim/commands/branch.go, cmd/resim/commands/project.go
Page token is not nil but empty
[Asana task](https://app.asana.com/0/1205228215063249/1205253276058404/f)
=> Checking Empty Page Token

cmd/resim/commands/branch.go, cmd/resim/commands/build.go
Fix typo in getBranch
[Asana task](https://app.asana.com/0/1205228215063249/1205253276058404/f)
=> Fix Typo In Branch

cmd/resim/commands/batch.go, cmd/resim/commands/branch.go, cmd/resim/commands/build.go, cmd/resim/commands/client.go, cmd/resim/commands/commands.go, cmd/resim/commands/experience.go, cmd/resim/commands/log.go, cmd/resim/commands/project.go
We have to register pflags before the subcommand is called, but we only want to register the flags for the subcommand that is running.  So we make a registration func and call it with the PreRun hook.
=> Fix pflags for experience.

cmd/resim/commands/client.go, cmd/resim/commands/experience.go
```
go run . --url=https://api.resim.io/v1 --auth_url=https://dev-jbs5inutkvkmnq7c.us.auth0.com experience create \
--name "Experience_56ccce99" \
--description "In this exprience, we test that our robot can navigate to the goal without colliding with any other agents." \
--location "s3://my-experiences-bucket/experience_56ccce99/"
```
=> Get API to work in dev.

.github/workflows/release-cli.yml
=> Fix github ref name in release.

.github/workflows/release-cli.yml
=> Use curl instead of go install to update pkg DB.

README.md
Update the binary install commands in the README
=> update README with new version

cmd/resim/cli.go, cmd/resim/commands/batch.go, cmd/resim/commands/branch.go, cmd/resim/commands/build.go, cmd/resim/commands/client.go, cmd/resim/commands/log.go
kebab-case is standard for CLI parameters.
[Docs update](https://github.com/resim-ai/docs/pull/16)
=> Change CLI parameters to kebab-case.

cmd/resim/commands/batch.go, cmd/resim/commands/branch.go, cmd/resim/commands/build.go, cmd/resim/commands/client.go, cmd/resim/commands/experience.go, cmd/resim/commands/log.go, cmd/resim/commands/project.go
Prevents segfaults when evaluating client responses.
=> Fix client error handling.

README.md, cmd/resim/commands/client.go, cmd/resim/commands/log.go
=> Kebab-case client-id and client-secret error messages.

cmd/resim/commands/batch.go, cmd/resim/commands/branch.go, cmd/resim/commands/build.go, cmd/resim/commands/experience.go, cmd/resim/commands/logs.go, cmd/resim/commands/project.go
Adds a list logs endpoint
[Asana task](https://app.asana.com/0/1205228215063249/1205290251624877/f)
=> Making Log Plural

cmd/resim/commands/batch.go, cmd/resim/commands/branch.go, cmd/resim/commands/build.go, cmd/resim/commands/client.go, cmd/resim/commands/commands.go, cmd/resim/commands/experience.go, cmd/resim/commands/experience_tags.go, cmd/resim/commands/logs.go, cmd/resim/commands/project.go
=> Cache client credentials.

README.md, testing/end_to_end_test.go
=> Adapting E2E test to new worker

CHANGELOG.md
=> make changelog match docs site format, add link to docs

.github/pull_request_template.md, CHANGELOG.md, api/client.gen.go, cmd/resim/commands/batch.go, testing/end_to_end_test.go
queued behind https://github.com/resim-ai/api-client/pull/55/files
=> batch create: add --metrics-build-id flag

CHANGELOG.md
=> Update CHANGELOG.md to include v0.1.22

CHANGELOG.md, cmd/resim/commands/experience_tags.go, testing/end_to_end_test.go
Not sure how to test this one meaningfully, open to suggestions.
=> add experience-tags list

testing/end_to_end_test.go
=> Latest Logs

CHANGELOG.md, README.md, go.mod
So we don't have undefined behaviour from `go install`
=> use a new release number

CHANGELOG.md, cmd/resim/commands/build.go, cmd/resim/commands/metrics_build.go, go.mod, go.sum, testing/end_to_end_test.go
In order to provide a nicer error message to customers, we validate image URIs on the CLI
```
```
=> Guard Against Invalid Image URIs

CHANGELOG.md, cmd/resim/commands/branch.go, cmd/resim/commands/project.go, go.mod, go.sum
Switches out our uuid parsing checks to validate before parsing.
```
go test -v -tags end_to_end -count 1 ./testing
```
=> Parsing Robustness

.devcontainer/Dockerfile, .devcontainer/build.sh, .devcontainer/devcontainer.json, .devcontainer/pull.sh, .devcontainer/run.sh, .devcontainer/run_dotfiles.sh, .devcontainer/run_dotfiles_local.sh, .devcontainer/run_local.sh, .github/workflows/build-image.yml, go.mod
=> Devcontainer for API Client

cmd/resim/commands/metrics_build.go
=> Metric Build Alias

CHANGELOG.md
=> Release v0.1.30

api/client.gen.go, cmd/resim/commands/batch.go, cmd/resim/commands/build.go, cmd/resim/commands/logs.go, cmd/resim/commands/sweep.go, testing/end_to_end_test.go
Update CLI to use new types generated from the rerun openAPI spec
Didn't test yet
=> Update CLI based on openAPI spec

api/client.gen.go, cmd/resim/commands/batch.go, cmd/resim/commands/branch.go, cmd/resim/commands/build.go, cmd/resim/commands/experience.go, cmd/resim/commands/experience_tags.go, cmd/resim/commands/logs.go, cmd/resim/commands/metrics_build.go, cmd/resim/commands/project.go, cmd/resim/commands/sweep.go, staticcheck.conf, testing/end_to_end_test.go
Adds a few extra type changes, plus removes staticcheck warnings.
=> Types and Warnings

CHANGELOG.md
=> Release v0.1.31

CHANGELOG.md, api/client.gen.go, cmd/resim/commands/batch.go, cmd/resim/commands/branch.go, cmd/resim/commands/experience.go, cmd/resim/commands/experience_tags.go, cmd/resim/commands/logs.go, cmd/resim/commands/metrics_build.go, cmd/resim/commands/sweep.go, testing/end_to_end_test.go
Extends the ReSim CLI to support the global project concept. This is a backwards incompatible change.
Run the end to end test.
=> Global Projects

.github/workflows/lint-and-build.yml
=> add e2e to CI

CHANGELOG.md, cmd/resim/commands/batch.go, testing/end_to_end_test.go
=> Cancel Batch

cmd/resim/commands/batch.go
=> Environment prefix bug

.devcontainer/Dockerfile, api/client.gen.go, cmd/resim/commands/experience.go, go.mod, go.sum
We update to a later version of GoLang, the devcontainer, and provide a more nuanced experience validation.
Run the e2e test.
=> Update Go and Tweak Experience Validation

CHANGELOG.md
=> Update Changelog for v0.3.5

CHANGELOG.md, cmd/resim/commands/client.go
This adds password authentication using the new CLI application and refactors the auth handling to be easier to understand
=> Support password authentication

CHANGELOG.md, api/client.gen.go, cmd/resim/commands/batch.go, cmd/resim/commands/experience_tags.go, cmd/resim/commands/report.go, cmd/resim/commands/sweep.go, cmd/resim/commands/test_suites.go, go.mod, go.sum
Introduces pool labels to batch, test suite, and parameter sweep creation to the resim CLI.
N/A
=> Pool Labels in CLI

CHANGELOG.md
Release api-client version 0.3.9.
=> Release 0.3.9

cmd/resim/commands/batch.go, cmd/resim/commands/report.go, cmd/resim/commands/sweep.go
=> Terminology changes

CHANGELOG.md, api/client.gen.go, cmd/resim/commands/project.go, cmd/resim/commands/system.go, testing/end_to_end_test.go
Edits the CLI to be explicit that projects and systems are archived now.
```
go test -v -tags end_to_end -count 1 ./testing
```
=> Archive Systems and Projects

CHANGELOG.md, api/client.gen.go, cmd/resim/commands/report.go, cmd/resim/commands/sweep.go, testing/end_to_end_test.go
Adds support for parameter sweep cancellation to the CLI.
=> Sweep Cancellation

.github/workflows/lint-and-build.yml, CHANGELOG.md
=> Noting the changes for v0.11.0

CHANGELOG.md, cmd/resim/commands/debug.go
=> wording tweaks

CHANGELOG.md, api/client.gen.go, cmd/resim/commands/batch.go, testing/end_to_end_test.go
=> ReRun Batch Metrics Only
