cmd/resim/commands/log.go

Fixes a bug in the CLI where the logs creation was not checking the correct status code.
[Asana task](https://app.asana.com/0/1205228215063249/1205290251624866/f)

Fixes CLI Bug for Create Log

---

cmd/resim/commands/batch.go
cmd/resim/commands/branch.go
cmd/resim/commands/build.go
cmd/resim/commands/client.go
cmd/resim/commands/experience.go
cmd/resim/commands/experience_tags.go
cmd/resim/commands/logs.go
cmd/resim/commands/project.go

Modifies the validate response code to not check the raw error, but we do that in-line. This is because if the error
exists, a response may be nil.
[Asana task](https://app.asana.com/0/1204958435152584/1205290251624895/f)
You can very easily repro a seg fault on main by passing fake credentials, then try with this PR.

Fixing possible seg faults

---

cmd/resim/commands/project.go

Allows the user to get and delete a project by name or id

User can get and delete project

---

cmd/resim/commands/commands.go
cmd/resim/commands/experience.go
cmd/resim/commands/styling.go
go.mod
go.sum

This PR sets us up to be able customize the style of help, usage and error 
messages. The effect of the PR is *almost* a noop on current behavior. It
makes a very small change to the styling of section headings in usage
messages (see images below), in order to demonstrate the functionality. 
The main aim of the PR is to set us up with the ability to make greater 
customization in the future. For example, the next PR (#45 ) will aim to 
separate Flags into required and optional sections per a customer request.
Old:
New:
[Asana task](https://app.asana.com/0/1205228215063249/1205227572053881/f)
run any `resim` command with `--help` and verify the new heading styling.

Getting Styley

---

cmd/resim/commands/styling.go
cmd/resim/commands/styling_test.go

Per user request we are styling the help messages such that required and optional flags 
are in separate sections. Here is an example from `resim experiences create`
```
USAGE
resim experiences create [flags]
REQUIRED FLAGS
--description string   The description of the experience
--location string      The location of the experience, e.g. an S3 URI for the experience folder
--name string          The name of the experience
OPTIONAL FLAGS
--github   Whether to output format in github action friendly format
-h, --help     help for create
``` 
If there are no required flags or no optional flags then the sections are omitted.
Here is an example from `resim --help`
```
AVAILABLE COMMANDS
batches     batches contains commands for creating and managing batches
branches    branches contains …
```

Separating required and optional flags in help messages

---

CHANGELOG.md
cmd/resim/commands/batch.go
testing/end_to_end_test.go

Will be useful in a GitHub workflow for getting the batch ID without resorting to grep, cut and friends.

add github flag to batch create

---

CHANGELOG.md
cmd/resim/commands/batch.go
cmd/resim/commands/branch.go
cmd/resim/commands/build.go
cmd/resim/commands/experience_tags.go
cmd/resim/commands/project.go

The CLI orders lists of projects, branches, builds, batches by timestamp.

CLI Orders Lists by Timestamp as Default

---

CHANGELOG.md
api/client.gen.go
cmd/resim/commands/batch.go
cmd/resim/commands/experience.go
cmd/resim/commands/experience_tags.go
cmd/resim/commands/uuid.go
testing/end_to_end_test.go

Adds new flags for `batch create` and adds commands to work with `experience-tags`

batch create supports new flags

---

CHANGELOG.md
api/client.gen.go
cmd/resim/commands/experience.go

Experiences can now be provided with an optional launch profile. Launch profile creation and editing are currently not supported elsewhere. This will be addressed in a follow-up PR.

Create Experience with Optional Launch Profile

---

CHANGELOG.md
api/client.gen.go
cmd/resim/commands/batch.go
cmd/resim/commands/sweep.go
testing/data/invalid_sweep_config.json
testing/data/valid_sweep_config.json
testing/end_to_end_test.go

Introduces the ability to create a parameter sweep, get a single sweep, and list all the sweeps.
`go test -v -tags end_to_end -count 1 ./testing`

Parameter Sweeps

---

CHANGELOG.md
cmd/resim/commands/client.go

With an expired token in my cache.json, I was getting:
```
./resim sweeps list
2023/11/29 10:20:11 error getting token: oauth2: "invalid_grant" "Unknown or invalid refresh token."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104886160]
goroutine 1 [running]:
github.com/resim-ai/api-client/cmd/resim/commands.(*CredentialCache).SaveCredentialCache(0x1400040d6b0)
/Users/ben/resim-ai/api-client/cmd/resim/commands/client.go:168 +0xb0
github.com/resim-ai/api-client/cmd/resim/commands.RegisterViperFlagsAndSetClient(0x14000420400?, {0x10488fc42?, 0x4?, 0x10488fbda?})
/Users/ben/resim-ai/api-client/cmd/resim/commands/commands.go:86 +0x200
github.com/spf13/cobra.(*Command).execute(0x104dcb8e0, {0x104e09380, …
```

check the cached token is valid before we try to reuse/cache it

---

CHANGELOG.md
cmd/resim/commands/batch.go
testing/end_to_end_test.go

Introduces an additional, optional (repeated) flag for specifying parameters to pass to a build when creating a batch. This enables a parameter override without having to create a sweep.
```CONFIG=staging go test -v -tags end_to_end -count 1 ./testing -testify.m TestParameterizedBatch```

Creating Batches with Parameters

---

api/client.gen.go
cmd/resim/commands/batch.go

The openapi generator generates a different type for the CreateBatch parameters which results in a compilation error without the tweak herein. I've made that tweak and regenerated the API code also.
```
go build -o resim ./cmd/resim
./resim --url https://api.resim.io/v1/ --auth-url https://resim-dev.us.auth0.com/ \
logs list \
--batch-id "09db113a-3bb7-46b1-8342-9ca552f0b5a6" \
--job-id "d490e95b-10fc-4861-af60-0e3435214c30"
```

Tweak code to match latest generation behavior

---

CHANGELOG.md
api/client.gen.go
cmd/resim/commands/experience.go

```
➜  api-client git:(ben/experience-validation) ✗ ./resim --url https://dev-env-pr-527.api.dev.resim.io/v1/ --auth-url https://resim-dev.us.auth0.com/ experience create --description 'testig vlaidation' --name "delete-me-again-12" --location 's3://dev-dev-env-pr-527-e2e/'
Creating an experience...
Created experience successfully!
Experience ID: 61bce4ab-924d-4362-8241-95ad5235ff2c
ReSim found 3 file(s) in experience location:
[
"experiences/914a1708-5682-4895-b0e3-f37d2abdb1af/ben.jpg",
"experiences/914a1708-5682-4895-b0e3-f37d2abdb1af/thing/woosh.jpeg",
"test-object/file.name"
]
➜  api-client git:(ben/experience-validation) ✗ ./resim --url https://dev-env-pr-527.api.dev.resim.io/v1/ --auth-url https://resim-dev.us.auth0.com/ experience create --description 'testig vlaidation' --name …
```

validate experience locations on experience creation

---

CHANGELOG.md
cmd/resim/commands/batch.go
cmd/resim/commands/branch.go
cmd/resim/commands/build.go
cmd/resim/commands/client.go
cmd/resim/commands/experience.go
cmd/resim/commands/experience_tags.go
cmd/resim/commands/logs.go
cmd/resim/commands/metrics_build.go
cmd/resim/commands/project.go
cmd/resim/commands/sweep.go

There was a bug in the previous versions of the CLI: any response errors were lost because the steam had already been read by the middleware. This meant when we tried to read again there was always an error "body closed". This change captures the error message and passes it through to validation steps.
N/A

Properly Report Error Response

---

CHANGELOG.md
cmd/resim/commands/batch.go
cmd/resim/commands/branch.go
cmd/resim/commands/build.go
cmd/resim/commands/client.go
cmd/resim/commands/commands.go
cmd/resim/commands/commands_test.go
cmd/resim/commands/experience.go
cmd/resim/commands/experience_tags.go
cmd/resim/commands/logs.go
cmd/resim/commands/metrics_build.go
cmd/resim/commands/project.go
cmd/resim/commands/sweep.go

This hooks up the config file writing-and-reading side of Viper, which was already being used to manage flags.
When writing to the config, we first read it into a blank Viper instance, so that we can persist different sets of flags from different call sites into the same config, while not persisting every single flag every time.
Also: Some minor rearrangement of the config-initialization functions in the aid of testability.
Also also: Moved the `RegisterViperFlagsAndSetClient` init call to the root command, where it flows down by default into every sub command.
```
$ rm ~/.resim/resim.json
$ cli project list
[... list of projects ]
$ cli branches list
2024/02/28 21:57:19 required flag(s) "project" not set
$ cli project select --project resim-sandbox-project
$ cli branches list
[
{ …
```

Use viper config file; allow persistence of project setting

---

CHANGELOG.md
cmd/resim/commands/batch.go
cmd/resim/commands/project.go

The `batches wait` command will allow CI jobs to pause and wait for test completion before handling. The command lifts some concepts from the `batches get` command like the (optional, in `get`) status-based exit codes.
To keep interfaces clean it is a separate command, not new options to `get`, with the fetch code factored out.
```
$ resim batches wait --project-id/-name ... 
```

Add "batches wait" command that will continuously poll until a batch reaches a final state.

---

cmd/resim/commands/experience.go
cmd/resim/commands/metrics_build.go
cmd/resim/commands/system.go
testing/end_to_end_test.go

PR 4 of 4 to introduce systems to the ReSim CLI. The intent is to squash all four of these PRs into one before landing.
In this PR, we add the final part of basic systems support: the ability to register and deregister experiences and metrics builds as compatible with a given system.
```
DEPLOYMENT=dev-env-pr-639  go test -v -tags end_to_end -count 1 ./testing
```

Systems CLI support #4: Adding and Removing systems

---

cmd/resim/commands/experience.go
cmd/resim/commands/metrics_build.go
cmd/resim/commands/system.go
testing/end_to_end_test.go

PR 3 of 4 to introduce systems to the ReSim CLI. The intent is to squash all four of these PRs into one before landing.
In this PR, we add the listing commands to systems. The builds listing is completely tested, the other two will be tested in the final PR.
```
DEPLOYMENT=dev-env-pr-639  go test -v -tags end_to_end -count 1 ./testing
```

Systems CLI support #3: Systems Listing Commands

---

cmd/resim/commands/build.go
cmd/resim/commands/experience.go
cmd/resim/commands/metrics_build.go
cmd/resim/commands/system.go
testing/end_to_end_test.go

PR 2 of 4 to introduce systems to the ReSim CLI. The intent is to squash all four of these PRs into one before landing.
In this PR, add the most basic system creation commands and ensure that the end to end test passes for this and existing commands.
```
DEPLOYMENT=dev-env-pr-639  go test -v -tags end_to_end -count 1 ./testing
```

Systems CLI support #2: System Create, Get, List

---

cmd/resim/commands/build.go

The CLI supports an `--auto-create-batch` flag that is used frequently in CI. This makes a decision about what type a main branch should be if it is ever triggered.

Map main to MAIN

---

CHANGELOG.md
api/client.gen.go
cmd/resim/commands/report.go
testing/end_to_end_test.go

Extends the CLI to allow reports to be created, obtained, and waited upon. The end to end test shall be extended with the latter functionality once implemented within the platform.

Report Management

---

CHANGELOG.md
cmd/resim/commands/batch.go
cmd/resim/commands/report.go
cmd/resim/commands/sweep.go

When creating a batch, sweep, or report include information about where it was triggered from.
https://app.asana.com/0/1206827738654243/1207474151607273
Create a batch locally, then via Github. You should see it noted in the `batches.triggered_via column`

Include trigger information in batches, sweeps, and reports

---

CHANGELOG.md
cmd/resim/commands/batch.go
cmd/resim/commands/commands.go
cmd/resim/commands/logs.go
testing/end_to_end_test.go

Small refactoring to the CLI to deprecate the use of the term jobs (still allowed via aliases). Test is now used.
In addition, we remove the ability to create a log via the CLI as this is not part of the non-customer facing API.
```
go test -v -tags end_to_end -count 1 ./testing
```

Rename jobs to test

---

cmd/resim/commands/client.go

This checks that the `auth-url` supplied has a trailing slash. Without one, the CLI returns an ambiguous error:
```
› resim projects list
2024/07/15 15:37:35 Initializing credential cache
2024/07/15 15:37:35 couldn't find CLI client ID for auth-url
```
We'd always expect it to have a trailing slash, so this will simply check for one, then add it if not.

Add check for trailing slash when supplying authURL

---

CHANGELOG.md
api/client.gen.go
cmd/resim/commands/build.go
cmd/resim/commands/metrics_build.go
cmd/resim/commands/system.go
cmd/resim/commands/test_suites.go
testing/end_to_end_test.go

Extends the ReSim CLI with the ability to update a system. In addition, we update the client to the latest release of the ReSim API, and enable show on summary for test suites.
Run the End to End test.

Show on Summary, Update Client, Update System

---

CHANGELOG.md
cmd/resim/commands/batch.go
go.mod
go.sum

Add --slack flag to `resim batch get` command which outputs information about the current batch in slack webhook format
Asana link: https://app.asana.com/0/1207187057163415/1208578818282141/f
PR with example in internal repo: https://github.com/resim-ai/core/pull/616
```
resim batch get --batch-name=reconfigured-ginger-clam --slack | curl -X POST -H 'content-type: application/json' --data @- $SLACK_WEBHOOK
```

Add slack webhook output to `resim batch get` command

---

CHANGELOG.md
cmd/resim/commands/commands.go
cmd/resim/commands/project.go

- Show `resim --help` when just running `resim` ([Asana task](https://app.asana.com/0/1208904700846047/1209391154283074))
- Fix `resim project select <>` ([Asana task](https://app.asana.com/0/1208904700846047/1209402535640595))

Show help by default and fix project selection

---

CHANGELOG.md
api/client.gen.go
cmd/resim/commands/experience.go
testing/end_to_end_test.go

Extends the ReSim CLI to support setting and updating experience timeouts. An experience can now be created with an optional `--timeout 3600` flag to specify how long they could be expected to run. The ReSim app will "ERROR" if the experience overruns. Any existing experiences can now be updated via `resim experiences update --experience <name-or-id> ...`.
This extends the E2E test to validate the timeouts work correctly.
```
go test -v -tags end_to_end -count 1 ./testing
```

Experience Timeouts

---

CHANGELOG.md
cmd/resim/commands/test_suites.go
testing/end_to_end_test.go

The ReSim App supports displaying the latest summary of a test suite's execution on the 'Overview' page. This change allows users of the CLI to revise existing test suites to either set or unset this flag.
Run the E2E test.

Revise Show On Summary

---

.github/workflows/lint-and-build.yml
CHANGELOG.md
cmd/resim/commands/batch.go
cmd/resim/commands/test_suites.go
cmd/resim/commands/utils.go
cmd/resim/commands/utils_test.go
testing/end_to_end_test.go

Modifies the `--parameter` flags for `batches create` and `suites run` to enable passing params that require colons in them. One can now use `param::name=param:value`. The `=` is now preferred, but a single colon is still supported.
```
go test ./...
```

Extra Delimiter

---

CHANGELOG.md
api/client.gen.go
cmd/resim/commands/branch.go
cmd/resim/commands/build.go
cmd/resim/commands/client.go
cmd/resim/commands/experience.go
cmd/resim/commands/experience_tags.go
cmd/resim/commands/ingest.go
cmd/resim/commands/report.go
testing/end_to_end_test.go

Introduces a CLI command designed to support customers who want to ingest logs from IRL (or HiL) robot testing and run a ReSim metrics build on it to generate results.
This is achieved by running a test batch with a single test containing that log.
This is a proof of concept, reusing the existing infrastructure that we have, which may or may not be the right thing to do.
```
```

Log Ingest

---

CHANGELOG.md
cmd/resim/commands/ingest.go
testing/end_to_end_test.go

Extends the ReSim CLI to support using a custom, existing build to ingest a log.

Allow Existing Builds to Be Used

---

CHANGELOG.md
cmd/resim/commands/test_suites.go
testing/end_to_end_test.go

Extends the CLI to allow the user to pass a `metrics-build-override` when running a test suite. This has the advantage of allowing you to test out a new metrics build in a test suite without having to pass through a large list of experiences like one would normally need to do for an ad hoc batch.
```
CONFIG=staging RESIM_CLIENT_ID=<> RESIM_CLIENT_SECRET=<> go test -v -tags end_to_end -count 1 ./testing -testify.m TestTestSuites
```

Metrics Build Override

---

CHANGELOG.md
cmd/resim/commands/logs.go
cmd/resim/commands/spinner.go
go.mod
go.sum
testing/end_to_end_test.go

Adds a subcommand to `resim logs` which downloads the logs for a given job.
Needs https://github.com/resim-ai/rerun/pull/1682 for test data.
Try it out!

PRO-126: Add resim logs download subcommand

---

cmd/resim/commands/ingest.go
testing/end_to_end_test.go

Extends the ReSim CLI's log ingestion functionality with a few variations in how to ingest logs that aim to support ingesting multiple logs at one time. 
First `--log "logname=s3path" --log "logname=s3path"` can be used. Alternatively, a YAML file:
```
logs:
- name: "log1"
location: "s3://bucket/path1"
- name: "log2"
location: "s3://bucket/path2"
```
Run t'end to end test

Bulk Log Ingest

---

CHANGELOG.md
cmd/resim/commands/logs.go
cmd/resim/commands/spinner.go
testing/end_to_end_test.go

- update `resim logs` commands to support batch logs
- update `resim logs download` to allow downloading a subset of files
- fix broken e2e test
Try it out!

PRO-178: Update logs commands to support batch logs and downloading a single file

---

.github/workflows/build-image.yml
.github/workflows/lint-and-build.yml
.github/workflows/release-cli.yml
CHANGELOG.md
api/client.gen.go
cmd/resim/commands/batch.go
cmd/resim/commands/build.go
cmd/resim/commands/ingest.go
cmd/resim/commands/test_suites.go
cmd/resim/commands/utils.go
testing/end_to_end_test.go

It is often desirable to pseudo-ingest logs and compute metrics on them before going through the expensive process of fully ingesting into cloud storage (particularly if there are bandwidth or cost concerns).
In this PR, we extend the log ingestion functionality of ReSim to support pool labels so that log ingestion can occur via the ReSim Agent.

Agent <> Log Ingest

---

.env.local.example
.envrc
.github/workflows/lint-and-build.yml
.gitignore
CHANGELOG.md
api/client.gen.go
bff/cmd/generate.go
cmd/resim/commands/build.go
cmd/resim/commands/ingest.go
cmd/resim/commands/report.go
cmd/resim/commands/system.go
testing/end_to_end_test.go

Updates the build model and CLI to transition from using `description` as the build's name to a new explicit `name` field, which is now required. `description` now sets the build's description, as one might expect it to.
Updates GraphQL schema handling to support dynamic endpoint configuration via environment variable.
Also adds client updates to support the new `buildSpecification` field for build specs in YAML format. 
Run `resim create-build` and `resim update-build` with `--name` and `--description` flags. Validate behavior through API client methods and verify deprecated fields still work for backward compatibility.

WOB-3105 | allow for updating of build names

---

CHANGELOG.md
cmd/resim/commands/ingest.go
testing/end_to_end_test.go

- Allow rerunning a log ingestion with the addition of the `--reingest` flag.

RSC-331: Log Ingest ReIngestion

---

CHANGELOG.md
api/client.gen.go
cmd/resim/commands/batch.go
testing/end_to_end_test.go

Introduces the ability to "rerun" a subset of the tests within a batch, via the `batches rerun` command. This will rerun any flaky or failing tests and then recompute any batch-level metrics.
Run the end to end test.

ReRun Batch

---

CHANGELOG.md
bff/queries.gen.go
bff/queries/update_metrics_config.graphql
cmd/resim/commands/metrics.go
testing/end_to_end_test.go

Metrics configs must now be synced to a specific project, not globally to only the org itself
https://linear.app/resim/issue/WOB-3501/associate-metrics-2-objects-to-projects
Add a .resim folder with a config like you see in: https://github.com/resim-ai/metrics-sync-testing
Test the command:
```shell
$ go run cmd/resim/cli.go --auth-url https://resim-dev.us.auth0.com --url https://api.resim.io/v1 metrics sync                              
2025/08/06 16:34:09 required flag(s) "project" not set
exit status 1
$ go run cmd/resim/cli.go --auth-url https://resim-dev.us.auth0.com --url https://dev-env-pr-2188.api.dev.resim.io/v1 metrics sync --project 'some-project-id' --verbose
Looking for metrics config at .resim/metrics/config.yml
Looking for templates in .resim/metrics/templates/
Found …
```

WOB-3501 | Require project id when syncing metrics config

---

CHANGELOG.md
cmd/resim/commands/batch.go
cmd/resim/commands/report.go
cmd/resim/commands/sweep.go
cmd/resim/commands/utils.go

Allow users to specify the metrics set they want when launching a batch, report, or sweep
```bash
resim batches create --metrics-set "hello world"
resim reports create --metrics-set "hello world"
resim sweep create --metrics-set "hello world"
```
https://linear.app/resim/issue/WOB-3542/add-metrics-set-to-resim-cli
Try one of the commands above.

WOB-3542 | Add metrics set flag to batches, reports, and sweeps
